const SB_URL="https://tqfocdktvjuwoiyfgesb.supabase.co";
const SB_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxZm9jZGt0dmp1d29peWZnZXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk5MDg0NTIsImV4cCI6MjEwNTQ4NDQ1Mn0.8TW4fQCQHc4c_xTNBEwOK3lSC9HYCbkTbfXuYQB-S8g";
const sb=window.supabase.createClient(SB_URL,SB_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const COPY=[{h:"The hour does not wait.",k:"Masthead",b:"Write something you would stand beside. If you mark it public, it may be chosen when the glass turns."},{h:"Paper remembers what screens forget.",k:"Editorial",b:"Private notes stay at your desk. Public ones walk the floor. Every sixty minutes we reprint the front."},{h:"A small press with a loud clock.",k:"Dispatch",b:"No algorithm. The hour picks from what people were willing to show."},{h:"Leave a mark, or keep it in the drawer.",k:"House style",b:"Accounts hold everything. Public is a choice, not a default."}];
let state={user:null,profile:null,view:"hour",piece:null,notice:""};
function hourKey(d=new Date()){const x=new Date(d);x.setMinutes(0,0,0);return x.toISOString()}
function fmtHour(iso){return new Date(iso).toLocaleString(undefined,{weekday:"short",hour:"numeric",minute:"2-digit"})}
function excerpt(s,n=160){s=(s||"").replace(/\s+/g," ").trim();return s.length>n?s.slice(0,n-1)+"…":s}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&","<":"<",">":">","\"":""","'":"&#39;"}[c]))}
function tick(){const now=new Date();const end=new Date(now);end.setMinutes(60,0,0);const ms=end-now;const m=Math.floor(ms/60000);const s=Math.floor((ms%60000)/1000);document.getElementById("remain").textContent=String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")}
async function ensureEdition(){const key=hourKey();const {data:existing}=await sb.from("ink_editions").select("*").eq("hour_key",key).maybeSingle();if(existing)return existing;const pick=COPY[Math.floor((Date.now()/3600000)%COPY.length)];const {data:publics}=await sb.from("ink_pieces").select("id,title,body").eq("is_public",true).order("created_at",{ascending:false}).limit(24);const featured=publics&&publics.length?publics[Math.floor(Math.random()*publics.length)]:null;const row={hour_key:key,piece_id:featured?featured.id:null,headline:featured?featured.title:pick.h,kicker:featured?"Featured slip":pick.k,body:featured?excerpt(featured.body,420):pick.b};const {data}=await sb.from("ink_editions").insert(row).select().maybeSingle();return data||row}
async function loadProfile(){if(!state.user){state.profile=null;return}const {data}=await sb.from("ink_profiles").select("*").eq("id",state.user.id).maybeSingle();state.profile=data}
function renderNav(){const nav=document.getElementById("nav");const items=[["hour","This hour"],["floor","The floor"],["desk","Desk"]];nav.innerHTML=items.map(([id,label])=>`<button class="${state.view===id?"active":""}" data-go="${id}">${label}</button>`).join("")+(state.user?`<button data-go="out">Sign out</button>`:`<button data-go="in">Sign in</button>`);document.getElementById("who").textContent=state.profile?"@"+state.profile.handle:(state.user?state.user.email:"Unsigned")}
async function viewHour(){const ed=await ensureEdition();let extra=ed.piece_id?`<div class="row"><button class="btn solid" data-open="${ed.piece_id}">Read the slip</button></div>`:"";document.getElementById("root").innerHTML=`<section class="hero"><div><div class="kicker">${esc(ed.kicker)} · ${fmtHour(ed.hour_key)}</div><h1 class="display">${esc(ed.headline)}</h1><p class="lede">${esc(ed.body)}</p><div class="meta-row"><span>Edition ${esc(ed.hour_key.slice(0,13).replace("T"," "))}</span><span>Public slips only</span></div>${extra}</div><div class="hourglass"><div class="cap"></div><div class="grain"></div><div class="sand"></div><div class="label">Turns on the hour</div></div></section>`}
async function viewFloor(){const {data}=await sb.from("ink_pieces").select("id,title,body,created_at").eq("is_public",true).order("created_at",{ascending:false}).limit(48);const cards=(data||[]).map((p,i)=>`<article class="card" style="animation-delay:${i*40}ms" data-open="${p.id}"><h3>${esc(p.title)}</h3><p>${esc(excerpt(p.body))}</p><footer><span>${new Date(p.created_at).toLocaleDateString()}</span><span>Public</span></footer></article>`).join("")||`<p class="lede">The floor is empty. Write something and mark it public.</p>`;document.getElementById("root").innerHTML=`<h2 class="section-title">On the floor</h2><div class="grid">${cards}</div>`}
async function viewPiece(id){const {data}=await sb.from("ink_pieces").select("*").eq("id",id).maybeSingle();if(!data){state.view="floor";return render()}document.getElementById("root").innerHTML=`<article class="piece-full"><div class="kicker">${data.is_public?"Public slip":"Private drawer"}</div><h1>${esc(data.title)}</h1><div class="meta-row"><span>${new Date(data.created_at).toLocaleString()}</span></div><div class="body">${esc(data.body)}</div><div class="row"><button class="btn ghost" data-go="floor">Back to the floor</button></div></article>`}
async function viewDesk(){if(!state.user)return viewAuth();if(!state.profile)return viewHandle();const {data}=await sb.from("ink_pieces").select("*").eq("author_id",state.user.id).order("created_at",{ascending:false});const mine=(data||[]).map(p=>`<article class="card" data-open="${p.id}"><h3>${esc(p.title)}</h3><p>${esc(excerpt(p.body))}</p><footer><span>${p.is_public?"Public":"Private"}</span><span data-toggle="${p.id}" data-pub="${p.is_public}" style="cursor:pointer">${p.is_public?"Hide":"Make public"}</span></footer></article>`).join("");document.getElementById("root").innerHTML=`<div class="panel"><div class="kicker">Your desk</div><h2 class="section-title">Set a piece down</h2><label>Title</label><input id="t" maxlength="140" /><label>Body</label><textarea id="b" maxlength="12000"></textarea><div class="row"><label class="toggle"><input type="checkbox" id="pub" /> Mark public</label><button class="btn solid" id="save">Save</button></div><div class="msg" id="m">${esc(state.notice)}</div></div><h2 class="section-title" style="margin-top:36px">Drawer</h2><div class="grid">${mine||"<p>Nothing saved yet.</p>"}</div>`;document.getElementById("save").onclick=savePiece}
function viewAuth(){document.getElementById("root").innerHTML=`<div class="panel"><div class="kicker">Account</div><h2 class="section-title">Sign in to keep the work</h2><label>Email</label><input id="em" type="email" /><label>Password</label><input id="pw" type="password" /><div class="row"><button class="btn solid" id="si">Sign in</button><button class="btn ghost" id="su">Create account</button></div><div class="msg" id="m"></div></div>`;document.getElementById("si").onclick=()=>auth("in");document.getElementById("su").onclick=()=>auth("up")}
function viewHandle(){document.getElementById("root").innerHTML=`<div class="panel"><div class="kicker">Masthead name</div><h2 class="section-title">Choose a handle</h2><label>Handle</label><input id="h" maxlength="32" /><label>Display name</label><input id="dn" maxlength="60" /><div class="row"><button class="btn solid" id="ok">Keep this</button></div><div class="msg" id="m"></div></div>`;document.getElementById("ok").onclick=saveHandle}
async function auth(mode){const email=document.getElementById("em").value.trim();const password=document.getElementById("pw").value;const m=document.getElementById("m");if(!email||password.length<6){m.textContent="Email and a password of at least six characters.";return}const fn=mode==="up"?sb.auth.signUp:sb.auth.signInWithPassword;const {data,error}=await fn({email,password});if(error){m.textContent=error.message;return}if(mode==="up"&&data.user&&!data.session){m.className="msg ok";m.textContent="Account created. If confirmations are on, check mail; otherwise sign in.";return}state.user=data.user;await loadProfile();state.view="desk";render()}
async function saveHandle(){const handle=document.getElementById("h").value.trim().toLowerCase().replace(/[^a-z0-9_]/g,"");const display_name=document.getElementById("dn").value.trim()||handle;const m=document.getElementById("m");if(handle.length<2){m.textContent="Handle needs two characters.";return}const {error}=await sb.from("ink_profiles").upsert({id:state.user.id,handle,display_name});if(error){m.textContent=error.message;return}await loadProfile();render()}
async function savePiece(){const title=document.getElementById("t").value.trim();const body=document.getElementById("b").value.trim();const is_public=document.getElementById("pub").checked;const m=document.getElementById("m");if(!title||!body){m.textContent="Title and body, both.";return}const {error}=await sb.from("ink_pieces").insert({author_id:state.user.id,title,body,is_public});if(error){m.textContent=error.message;return}state.notice=is_public?"Saved and on the floor.":"Saved in the drawer.";render()}
async function togglePublic(id,currently){await sb.from("ink_pieces").update({is_public:!currently,updated_at:new Date().toISOString()}).eq("id",id);render()}
async function render(){renderNav();if(state.view==="hour")await viewHour();else if(state.view==="floor")await viewFloor();else if(state.view==="desk")await viewDesk();else if(state.view==="in")viewAuth();else if(state.view==="piece")await viewPiece(state.piece)}
document.body.addEventListener("click",async e=>{const go=e.target.closest("[data-go]");if(go){const v=go.getAttribute("data-go");if(v==="out"){await sb.auth.signOut();state.user=null;state.profile=null;state.view="hour"}else state.view=v;render()}const open=e.target.closest("[data-open]");if(open){state.view="piece";state.piece=open.getAttribute("data-open");render()}const tog=e.target.closest("[data-toggle]");if(tog)togglePublic(tog.getAttribute("data-toggle"),tog.getAttribute("data-pub")==="true")});
sb.auth.onAuthStateChange(async(_e,session)=>{state.user=session&&session.user||null;await loadProfile();renderNav()});
(async function init(){tick();setInterval(tick,1000);const {data:{session}}=await sb.auth.getSession();state.user=session&&session.user||null;await loadProfile();await render();setInterval(()=>{if(state.view==="hour")viewHour()},30000)})();
